version: '3.8'

services:
  nginx:
    image: nginx:${NGINX_VERSION}-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./volumes/nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./volumes/nginx/conf.d:/etc/nginx/conf.d
      - ./volumes/nginx/ssl:/etc/nginx/ssl
      - ./files/php:/var/www/html
  
  php:
    image: php:${PHP_VERSION}-fpm-alpine
    container_name: php
    volumes:
      - ./volumes/php/conf.d:/usr/local/etc/php/conf.d
      - ./files/php:/var/www/html
